seed_everything: 7
trainer:
  callbacks:
    - class_path: pytorch_lightning.callbacks.LearningRateMonitor
      init_args:
        logging_interval: epoch
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        save_top_k: 1
        monitor: val_ExpRate
        mode: max
        filename: '{epoch}-{step}-{val_ExpRate:.4f}'
  logger:
    - class_path: pytorch_lightning.loggers.WandbLogger
      init_args:
        project: "SwinCoMER"
        name: "kaggle-run"
        save_dir: "."
        log_model: false
  devices: 1
  accelerator: "gpu"
  check_val_every_n_epoch: 2
  max_epochs: 150  # Giữ nguyên giá trị từ file cũ
  deterministic: true
model:
  d_model: 256
  # encoder
  swin_variant: "microsoft/swinv2-tiny-patch4-window8-256"
  # decoder
  nhead: 8
  num_decoder_layers: 4
  dim_feedforward: 2048
  dropout: 0.3
  dc: 32
  cross_coverage: true
  self_coverage: true
  # beam search
  beam_size: 10
  max_len: 200
  alpha: 1.0
  early_stopping: false
  temperature: 1.0
  # training
  learning_rate: 1e-4
  patience: 15
data:
  zipfile_path: "customdataset.zip"
  train_batch_size: 4
  eval_batch_size: 2
  num_workers: 5
  scale_aug: true