alpha: 1.0
beam_size: 10
cross_coverage: true
d_model: 256
dc: 32
dim_feedforward: 2048
dropout: 0.3
early_stopping: false
learning_rate: 0.0001
max_len: 200
nhead: 8
num_decoder_layers: 4
patience: 15
self_coverage: true
swin_variant: microsoft/swinv2-tiny-patch4-window8-256
temperature: 1.0
